### PR TITLE
Add remote to local ip address cache

### PR DESCRIPTION
**Pull request by VictorLowther**
Right now, this does nothing, but it will be used to tie into a dynamic templating system.

@galthaus can you test this on your mac?  I think the hack I am using for local address determination only works on Linux, and I would like a test on a mac.

### CODE REVIEW

**Comment by galthaus** [comment]
@VictorLowther - I get this:

rocket-skates 2017/04/02 02:14:17.148414 xid 0x51a7f10d: Discovery handing out: 192.168.100.110 to 08:00:27:33:77:de via 192.168.100.1
rocket-skates 2017/04/02 02:14:19.123197 Recieved DHCP packet: type Request xid 0x51a7f10d ciaddr 0.0.0.0 yiaddr 0.0.0.0 giaddr 0.0.0.0 chaddr 08:00:27:33:77:de
rocket-skates 2017/04/02 02:14:19.123248 Found our lease for strat: MAC token 08:00:27:33:77:de, will use it
rocket-skates 2017/04/02 02:14:19.125192 Recieved option: OptionClientArchitecture: 0
rocket-skates 2017/04/02 02:14:19.125198 Recieved option: OptionVendorClassIdentifier: PXEClient:Arch:00000:UNDI:002001
rocket-skates 2017/04/02 02:14:19.125201 Recieved option: OptionClientIdentifier:'3w?
rocket-skates 2017/04/02 02:14:19.125203 Recieved option: OptionServerIdentifier: 192.168.100.1
rocket-skates 2017/04/02 02:14:19.125206 Recieved option: OptionRequestedIPAddress: 192.168.100.110
rocket-skates 2017/04/02 02:14:19.125213 Recieved option: OptionDHCPMessageType: 3
rocket-skates 2017/04/02 02:14:19.125215 Recieved option: OptionMaximumDHCPMessageSize: 1472
rocket-skates 2017/04/02 02:14:19.125217 Recieved option: OptionCode(94): 
rocket-skates 2017/04/02 02:14:19.125221 Recieved option: OptionUserClass: iPXE
rocket-skates 2017/04/02 02:14:19.125223 Recieved option: OptionParameterRequestList: 
rocket-skates 2017/04/02 02:14:19.125225 Recieved option: OptionCode(175): 
rocket-skates 2017/04/02 02:14:19.125227 Recieved option: OptionCode(97): 
rocket-skates 2017/04/02 02:14:19.125483 xid 0x51a7f10d: Request handing out: 192.168.100.110 to 08:00:27:33:77:de via 192.168.100.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1483f72]

goroutine 75 [running]:
github.com/rackn/rocket-skates/vendor/github.com/pin/tftp.(*Server).processRequest6(0xc4206d08c0, 0xc42020e050, 0xc420214060, 0x0)
	/Users/galthaus/play-swagger/src/github.com/rackn/rocket-skates/vendor/github.com/pin/tftp/server.go:156 +0x142
github.com/rackn/rocket-skates/vendor/github.com/pin/tftp.(*Server).Serve(0xc4206d08c0, 0xc4201c07e0)
	/Users/galthaus/play-swagger/src/github.com/rackn/rocket-skates/vendor/github.com/pin/tftp/server.go:125 +0x27e
created by github.com/rackn/rocket-skates/midlayer.ServeTftp
	/Users/galthaus/play-swagger/src/github.com/rackn/rocket-skates/midlayer/tftp.go:56 +0x18c

**Comment by galthaus** [comment]
I'm not sure it compiled correctly.  I noticed you have a fork of the tftp code, but I don't think I picked up with tools/build.sh.  I think, but I'm tired and may not be thinking right.

**Comment by VictorLowther** [comment]
Yeah, it appears to be a difference in when ControlMessages are filled in on darwin.  I will add fallback code in tftp.

**Comment by galthaus** [comment]
This seems to work for me.  Should I pull it?

**Pull request merged**
