### PR TITLE
Refactor some asset handling and build code

### PR DESCRIPTION
**Pull request by VictorLowther**

### CODE REVIEW

**Comment by galthaus** [comment]
Looks good.  Will need to test to make sure it works on Mac

**Comment by zehicle** [comment]
@VictorLowther does this move swagger up a level in the embedded assets?

**Comment by VictorLowther** [comment]
Yes, it does.  I updated the references in frontend -- is there anything else that needs changing?

**Comment by zehicle** [comment]
I'd move the UI folder up a level then too.

**Comment by VictorLowther** [comment]
Everything still lives at embedded/assets in the Git repo.  I only stripped out the leading assets/ stuff for the Go embedding code.

**Comment by zehicle** [comment]
+! then :lgtm:

**Pull request merged**
